import type { SolveResult } from '@meltek/engine';
import { Callout } from '../components/primitives';
const n = (v: number | null, unit='') => v == null ? 'Not available' : `${v.toFixed(4)} ${unit}`;
export function EngineeringResults({result}:{result:SolveResult}) {
  const r=result.engineering!;
  const rows: [string,number|null,string][] = [['Winding layers',r.layers,''],['Turns per layer',r.turnsPerLayer,''],['Radial winding build',r.windingBuildMm,'mm'],['Finished axial width',r.finishedWidthMm,'mm'],['Wire per strand',r.wireLengthPerStrandM,'m'],['Total wire',r.totalWireLengthM,'m'],['Resistance at 20 °C',r.resistance20Ohm,'Ω'],['Resistance at room temperature',r.resistanceRoomOhm,'Ω'],['Resistance at 75 °C',r.resistance75Ohm,'Ω'],['Operating resistance',r.resistanceOperatingOhm,'Ω'],['Effective steel area',r.effectiveAreaCm2,'cm²'],['Working flux',r.operatingFluxT,'T'],['Required design voltage',r.voltageAtLimit,'V'],['Characterised saturation voltage',r.saturationVoltage,'V'],['Estimated knee voltage',r.kneeVoltage,'V'],['Area from specified Vk',r.areaFromKneeCm2,'cm²'],['Area from PS resistance formula',r.areaFromResistanceCm2,'cm²'],['Exciting current at check voltage',r.excitationCurrentA,'A'],['Working excitation',r.excitationAtCm,'AT/cm'],['Composite error estimate',r.compositeErrorEstimatePercent,'%'],['Steel + copper including waste',r.materialCost,'₹'],['Manufacturing cost',r.manufacturingCost,'₹']];
  return <div className="flex flex-col gap-4 p-4"><Callout tone={r.issues.length?'warn':'info'} title={r.issues.length?'Engineering screening needs attention':'Configured screening checks passed'}>Sinusoidal steady-state estimates. Protection composite error is excitation-based; knee voltage uses supplied characterised knee flux. These results do not establish standard compliance or transient fault performance. R75 source: {r.resistance75Source}.</Callout>
    {r.issues.length>0 && <ul className="list-disc pl-5 text-sm">{r.issues.map(i=><li key={i}>{i}</li>)}</ul>}
    <dl className="grid grid-cols-1 gap-3 md:grid-cols-3">{rows.map(([label,v,u])=><div key={label} className="rounded-md border border-[var(--line)] p-3"><dt className="text-xs text-[var(--text-2)]">{label}</dt><dd className="mt-1 num text-sm">{n(v,u)}</dd></div>)}</dl>
    {!!r.checks.length && <div className="overflow-x-auto"><table className="data-table w-full text-xs"><thead><tr>{['Current %','Burden %','Ratio error %','Phase minutes','Screening'].map(h=><th className="p-2 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{r.checks.map((p,i)=><tr key={i}><td className="p-2">{p.currentPercent}</td><td>{p.burdenPercent}</td><td>{n(p.ratioErrorPercent)}</td><td>{n(p.phaseMinutes)}</td><td>{p.passed===null?'Missing curve data':p.passed?'Pass':'Fail'}</td></tr>)}</tbody></table></div>}
    <div className="overflow-x-auto"><table className="data-table w-full text-xs"><thead><tr><th className="p-2">Calculation</th><th>Formula</th><th>Result</th></tr></thead><tbody>{result.steps.map(s=><tr key={s.key}><td className="p-2">{s.label}</td><td>{s.formula}</td><td className="p-2 num">{typeof s.value==='number'?n(s.value,s.unit):s.value}</td></tr>)}</tbody></table></div>
  </div>;
}
